modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-orenoconfig/issues"
license = "ARR"

[[mods]]
modId = "orenoconfig"
version = "${version}"
displayName = "Oreno Config"
authors = "mahmudindev"
description = '''
Provide config across mod loader.
'''
logoFile = "assets/orenoconfig/icon.png"

[[dependencies.orenoconfig]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.orenoconfig]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "orenoconfig.mixins.json"
